# Generated by Django 4.2.13 on 2024-07-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="comfortablility", new_name="comfortability",
        ),
    ]
