# Generated by Django 4.2.13 on 2024-06-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0004_cafe_thumbnail_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="cafe", name="thumbnail_url",),
    ]
