# Generated by Django 4.2.13 on 2024-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0005_remove_cafe_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="thumbnail_image_location",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
