# Generated by Django 4.2.13 on 2024-07-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0006_cafe_thumbnail_image_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="google_maps_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
