# Generated by Django 4.2.13 on 2024-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0007_cafe_google_maps_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="cafe", name="thumbnail_image_location",),
        migrations.AddField(
            model_name="cafe",
            name="thumbnail_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
