# Generated by Django 4.2.13 on 2024-07-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0008_remove_cafe_thumbnail_image_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="thumbnail_image",
            field=models.ImageField(blank=True, null=True, upload_to="cafes/"),
        ),
    ]
