# Generated by Django 4.2.13 on 2024-07-14 06:13

import cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0009_cafe_thumbnail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=cafe.models.get_cafe_thumbnail_path
            ),
        ),
    ]
